### ISSUE TITLE
An error is showing installing via composer

### ISSUE THREAD

**Issue by iamsarath1986** [contao/standard-edition#31] opened 2016-01-12 11:46 UTC
Installing via composer an error is showing (windows 10, XAMPP, Contao 4.1.0). 

Contao\CoreBundle\Composer\ScriptHandler::generateSymlinks

  [Symfony\Component\Filesystem\Exception\IOException]
  Failed to create symbolic link from "C:\Users\user-pc\contoa/vendor/contao/core-bundle/src/Resources/contao/themes/flexible" to "C:\Users\user-pc\contoa/system/themes/flexible".

contao:symlinks

Script Contao\CoreBundle\Composer\ScriptHandler::generateSymlinks handling the post-install-cmd event terminated with an exception

  [RuntimeException]
  An error occurred while executing the "contao:symlinks" command.

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

**Comment by aschempp** [comment] 2016-01-12 18:09
Duplicate of https://github.com/contao/core-bundle/issues/432

**Comment by iamsarath1986** [comment] 2016-01-15 05:35
I have checked the link but it is an UBUNTU problem.

**Comment by iamsarath1986** [comment] 2016-01-15 07:26
Is this version support windows?

**Closed as completed** 2016-02-11 11:46 UTC
Labels: duplicate
